### ISSUE TITLE
Getting data to the map?

### ISSUE THREAD

**Issue by kellyzdude** [andmcgregor/dashing-map#1]
Seems I'm missing something obvious, but I can't figure it out. I also must concede I'm almost brand new to ruby and to dashing, which isn't helping.

How does one get the pinpoint (or heat) data to the map, either statically or dynamically?

I have a dashboard on which I want to show a map including our datacenter locations using the standard Google Maps markers. If possible, I would like to associate a scheduled job to update the markers with the status (up/down should be sufficient, just to mark the pin Green for up or Red for down).

Is there any chance of updating the documentation to include the critical detail of providing the location data to the map?

Thanks!

**Comment by andmcgregor** [comment]
The example application uses a job in order to update map data. It should be no different than getting data into other widgets, e.g.

``` ruby
markers = [[40.7042711, -73.99463564],[40.72068318, -74.0360876],[40.69018566, -73.99902579],[40.71371072, -74.00686788]]

send_event('map', { markers: markers })
```

This was 8 months ago but from memory I was initially updating the map data with a curl request also.

**Comment by kellyzdude** [comment]
That makes sense, no job file was included in the package and that was the first thing I looked for. I found a twitter message from a few months ago which pointed me towards trying the curl method in several forms but to no avail.

I'm not a (complete) idiot, though I am a sysadmin more than a developer, and my development abilities are pretty well limited to PHP and Bash with limited hacking skills with other systems to have them do my will (in this case, those skills are failing me). To be sure I had a clean slate, I re-downloaded the map.coffee file. I had hacked at it a fair bit trying to understand what I was getting wrong and trying to make it work. I'm now working on a clean copy of the file that is currently un-modified.

I created 'maps.rb' in the jobs directory using the 'dashing generate job map' command and modified it based on your tip, eventually it may have an array of marker lists which we'll cycle through every 20-30s or so:

```
markers = [[40.7042711, -73.99463564],[40.72068318, -74.0360876],[40.69018566, -73.99902579],[40.71371072, -74.00686788]]

SCHEDULER.every '1m', :first_in => 0 do |job|
  send_event('map', { markers: markers })
end
```

I've also tried the following:
`curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "markers": "[[40.7042711, -73.99463564],[40.72068318, -74.0360876],[40.69018566, -73.99902579],[40.71371072, -74.00686788]]" }' \http://localhost:3030/widgets/map`

(I verified with the sample 'text' widget and ensured the overall functionality of the API worked)

In both cases it fails to change the map in any way, I'm not sure what I'm missing. Any ideas/suggestions?

**Comment by andmcgregor** [comment]
I just made this repo showing an example of the setup:

https://github.com/andmcgregor/dashing-map-example.

Maybe use this as reference.

The only changes from the default dashing application I made was 1) adding the google maps include to the top of the layout.erb file (with my own google maps API key), 2) installing the widget as described in the README, 3) adding the html to the dashboard as described in the README and 4) generating a job like you have above.

**Comment by derwin12** [comment]
This works for me:
curl -d '{ "auth_token": "MY_TOKEN",  "markers": [[10,100],[-10,50],[10.72046961,-74.0089763
1],[10.72499544,-74.01220975]] }'  http://localhost:3030/widgets/samplemap

Trying to figure out .. and I may have to code(?) things like zoom.
I havent been able to switch from heat to non-heat via curl either.

**Comment by andmcgregor** [comment]
@derwin12 adding data-type="heat" to the div element makes the map a heatmap rather than pins. It currently isn't possible to achieve via curl.

Zoom/viewable area of the map should automatically update based on the markers sent to the map, but you might want to edit to code to achieve what you want.

**Comment by derwin12** [comment]
Thanks .. what is the other type? data-type="????" When I try something like junk/point i get nothing

Could you post what you used to produce your first pic for example?
send( ... etc. )

**Comment by andmcgregor** [comment]
@derwin12 there are only two options currently for the map, regular markers (by using no data-type) and heatmap.

Closing this since there does not seem to be a specific issue/bug.
